version: '3.8'

services:
  bob-coordinator:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: bob-coordinator
    hostname: bob-coordinator
    environment:
      - COLLECTIVE_MODE=coordinator
      - COLLECTIVE_MEMBER_ID=bob
      - COLLECTIVE_AUTO_TLS=true
    ports:
      - "8001:8001"  # Expose coordinator for peering
    volumes:
      - bob-certs:/collective/certs
      - bob-coord-data:/data
    command: |
      sh -c '
      # Auto-generate certificates on first run
      if [ ! -f /collective/certs/ca/bob-ca.crt ]; then
        collective auth auto-init --member-id bob --component-type coordinator
      fi
      # Start coordinator with Alice as bootstrap peer
      collective coordinator \
        --member-id bob \
        --address :8001 \
        --bootstrap-peers alice:alice.homelab.com:8001 \
        --config /tmp/collective-config/config.json
      '
    networks:
      - collective-net
    restart: unless-stopped

  bob-node-01:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: bob-node-01
    environment:
      - COLLECTIVE_MODE=node
      - COLLECTIVE_MEMBER_ID=bob
      - COLLECTIVE_NODE_ID=bob-node-01
      - COLLECTIVE_AUTO_TLS=true
    volumes:
      - bob-certs:/collective/certs
      - bob-node-01-data:/data
    command: |
      collective node \
        --member-id bob \
        --node-id bob-node-01 \
        --coordinator bob-coordinator:8001 \
        --capacity 1TB \
        --config /tmp/collective-config/config.json
    depends_on:
      - bob-coordinator
    networks:
      - collective-net
    restart: unless-stopped

  bob-node-02:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: bob-node-02
    environment:
      - COLLECTIVE_MODE=node
      - COLLECTIVE_MEMBER_ID=bob
      - COLLECTIVE_NODE_ID=bob-node-02
      - COLLECTIVE_AUTO_TLS=true
    volumes:
      - bob-certs:/collective/certs
      - bob-node-02-data:/data
    command: |
      collective node \
        --member-id bob \
        --node-id bob-node-02 \
        --coordinator bob-coordinator:8001 \
        --capacity 1TB \
        --config /tmp/collective-config/config.json
    depends_on:
      - bob-coordinator
    networks:
      - collective-net
    restart: unless-stopped

volumes:
  bob-certs:
  bob-coord-data:
  bob-node-01-data:
  bob-node-02-data:

networks:
  collective-net:
    driver: bridge