# Development docker-compose file that builds locally
# Use this when developing and testing changes before pushing
#
# Usage: docker compose -f docker-compose.dev.yml up -d --build

version: '3.8'

services:
  alice-coordinator:
    build: ../..
  
  bob-coordinator:
    build: ../..
  
  carol-coordinator:
    build: ../..
  
  alice-node-01:
    build: ../..
  
  alice-node-02:
    build: ../..
  
  bob-node-01:
    build: ../..
  
  bob-node-02:
    build: ../..
  
  carol-node-01:
    build: ../..
  
  carol-node-02:
    build: ../..
  
  alice-node-03:
    build: ../..
  
  bob-node-03:
    build: ../..
  
  carol-node-03:
    build: ../..