version: '3.8'

services:
  alice-coordinator:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: alice-coordinator
    hostname: alice-coordinator
    environment:
      - COLLECTIVE_MODE=coordinator
      - COLLECTIVE_MEMBER_ID=alice
      - COLLECTIVE_AUTO_TLS=true
    ports:
      - "8001:8001"  # Expose coordinator for peering
    volumes:
      - alice-certs:/collective/certs
      - alice-coord-data:/data
    command: |
      sh -c '
      # Auto-generate certificates on first run
      if [ ! -f /collective/certs/ca/alice-ca.crt ]; then
        collective auth auto-init --member-id alice --component-type coordinator
      fi
      # Start coordinator with Bob as bootstrap peer
      collective coordinator \
        --member-id alice \
        --address :8001 \
        --bootstrap-peers bob:bob.homelab.com:8001 \
        --config /tmp/collective-config/config.json
      '
    networks:
      - collective-net
    restart: unless-stopped

  alice-node-01:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: alice-node-01
    environment:
      - COLLECTIVE_MODE=node
      - COLLECTIVE_MEMBER_ID=alice
      - COLLECTIVE_NODE_ID=alice-node-01
      - COLLECTIVE_AUTO_TLS=true
    volumes:
      - alice-certs:/collective/certs
      - alice-node-01-data:/data
    command: |
      collective node \
        --member-id alice \
        --node-id alice-node-01 \
        --coordinator alice-coordinator:8001 \
        --capacity 500GB \
        --config /tmp/collective-config/config.json
    depends_on:
      - alice-coordinator
    networks:
      - collective-net
    restart: unless-stopped

  alice-node-02:
    image: ghcr.io/colegreenlee/collective:latest
    container_name: alice-node-02
    environment:
      - COLLECTIVE_MODE=node
      - COLLECTIVE_MEMBER_ID=alice
      - COLLECTIVE_NODE_ID=alice-node-02
      - COLLECTIVE_AUTO_TLS=true
    volumes:
      - alice-certs:/collective/certs
      - alice-node-02-data:/data
    command: |
      collective node \
        --member-id alice \
        --node-id alice-node-02 \
        --coordinator alice-coordinator:8001 \
        --capacity 500GB \
        --config /tmp/collective-config/config.json
    depends_on:
      - alice-coordinator
    networks:
      - collective-net
    restart: unless-stopped

volumes:
  alice-certs:
  alice-coord-data:
  alice-node-01-data:
  alice-node-02-data:

networks:
  collective-net:
    driver: bridge