name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  GO_VERSION: '1.23'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      
      - name: Install dependencies
        run: go mod download
      
      - name: Run go fmt check
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Please run go fmt"
            gofmt -s -d .
            exit 1
          fi
      
      - name: Run go vet
        run: go vet ./...
      
      - name: Run unit tests
        run: go test -v -race -short ./pkg/...
      
      - name: Build binary
        run: go build -o collective ./cmd/collective/